### ISSUE TITLE
ImportError about nms 

### ISSUE THREAD

**Issue by xiaominzhen** [OpenPerceptionX/PersFormer_3DLane#1]
<img width="1920" alt="企业微信截图_33fdb53c-79e1-464d-b04f-b7a7fc5c8216" src="https://user-images.githubusercontent.com/99106655/162959235-ba74e878-32b8-4b61-8d1d-bbc71ae58041.png">

I have setup the environment successfully, but when I run "python3 -m torch.distributed.launch --nproc_per_node 1 main_persformer.py --mod=PersFormer --batch_size=4 --nepochs=10" , it made an ImportError.

Could you please help me see how to solve it? very thanks!

**Comment by xiaominzhen** [comment]
I have solved the problem by updating torch by "pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html", hope it will be helpful to others

**Comment by ChonghaoSima** [comment]
Have you compile the nms operator successfully?
