### ISSUE TITLE
Visualization Code

### ISSUE THREAD

**Issue by WYL-Projects** [OpenPerceptionX/PersFormer_3DLane#10]
Hello Author，
Thank you for the findings, I didn't find in the code the code to visualize the Openlane dataset during the evaluation, only the calculation of the precision.

**Comment by dyfcalid** [comment]
The visualization code is in `utils.py`, see https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/15fbe75b8d2a27fa323d5432ace3428a2af44253/utils/utils.py#L133

**Comment by WYL-Projects** [comment]
@dyfcalid 
Thank you for your replying
