### ISSUE TITLE
How to test my own images?

### ISSUE THREAD

**Issue by HaonanLu9566** [OpenPerceptionX/PersFormer_3DLane#12]
Dear author,
I want to know how to test my own images if there is no ground truth value of my images? 
Thanks for opensource this outstanding working!

您好，感谢开源如此优秀的工作！请问一下怎么才能测试自己的图片呢？是必须要有图片的ground truth吗？如果没有的话怎么办呢？

**Comment by dyfcalid** [comment]
Thank you. 
You can refer to the [issue#7](https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/7#issuecomment-1113378547) or [issue#8](https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/8#issuecomment-1114240884) which has mentioned before. Maybe we will update the inference code in the future.

**Comment by HaonanLu9566** [comment]
> Thank you. You can refer to the [issue#7](https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/7#issuecomment-1113378547) or [issue#8](https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/8#issuecomment-1114240884) which has mentioned before. Maybe we will update the inference code in the future.

Thanks for your reply.
I have temporary solved this problem, looking forward to the inference code!
Further more, hope for more helpful code on how to transfer to onnx and TensorRT in the future!

**Comment by RohitKeshari** [comment]
@HaonanLu9566  can you share your solution
