### ISSUE TITLE
Model weight loading error

### ISSUE THREAD

**Issue by WYL-Projects** [OpenPerceptionX/PersFormer_3DLane#13]
We used the best trained model provided in the article for testing, but the weight of the model was loaded incorrectly. The reason seems to be that the keys of the model parameters don't match, that is, the model parameters don't match. However, the hyperparameters I used have always been the hyperparameters in the code and haven't been changed. The error results are as follows:
![图片](https://user-images.githubusercontent.com/50573960/168013757-980f77c4-bd69-4fab-95d3-2b0c11dc99cd.png)

**Comment by dyfcalid** [comment]
We update the model code and corresponding checkpoint, so you need to download the newest file from [here](https://drive.google.com/file/d/1QE5Vt6jJl1uyduEi5tj7_0iN6-_Mpqbp/view?usp=sharing).

**Comment by callzhang** [comment]
Hi @dyfcalid , I used your weights and the size is mismatched:
```python
Exception has occurred: RuntimeError
Error(s) in loading state_dict for PersFormer:
	size mismatch for laneatt_head.attention_layer.weight: copying a param with shape torch.Size([111, 1408]) from checkpoint, the shape in current model is torch.Size([2783, 1408]).
	size mismatch for laneatt_head.attention_layer.bias: copying a param with shape torch.Size([111]) from checkpoint, the shape in current model is torch.Size([2783]).
  File "/home/derek/PersFormer_3DLane/experiments/runner.py", line 502, in eval
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/derek/PersFormer_3DLane/main_persformer.py", line 39, in main
    runner.eval()
  File "/home/derek/PersFormer_3DLane/main_persformer.py", line 43, in <module>
    main()
```

**Comment by ilnehc** [comment]
@callzhang Please see the related issue above. This checkpoint is outdated and we are not allowed to provide a pretrained model.

**Comment by PeterJaq** [comment]
> Hi @dyfcalid , I used your weights and the size is mismatched:
> 
> ```python
> Exception has occurred: RuntimeError
> Error(s) in loading state_dict for PersFormer:
> 	size mismatch for laneatt_head.attention_layer.weight: copying a param with shape torch.Size([111, 1408]) from checkpoint, the shape in current model is torch.Size([2783, 1408]).
> 	size mismatch for laneatt_head.attention_layer.bias: copying a param with shape torch.Size([111]) from checkpoint, the shape in current model is torch.Size([2783]).
>   File "/home/derek/PersFormer_3DLane/experiments/runner.py", line 502, in eval
>     model.load_state_dict(checkpoint['state_dict'])
>   File "/home/derek/PersFormer_3DLane/main_persformer.py", line 39, in main
>     runner.eval()
>   File "/home/derek/PersFormer_3DLane/main_persformer.py", line 43, in <module>
>     main()
> ```

Hello, I meet same problem with you, when I want to test PersFormer by my own dataset. And I try to use provided best model, the error is same. Do you solve this problem?
