### ISSUE TITLE
关于测试指标的问题

### ISSUE THREAD

**Issue by cedricgsh** [OpenPerceptionX/PersFormer_3DLane#14]
非常抱歉再次打扰你们。我尝试将gt作为预测样例来评价测试指标。具体的做法是这样的， 先将gt的格式转换成pred的格式，然后再在使用eval_3D_lane.py来测试，其中`--dataset_dir`的输入是原始标注，`--pred-dir`的输入是将gt转换成pred格式的输入。
<img width="335" alt="3fb1c67e4d4c1fd265c22a36dd627ca" src="https://user-images.githubusercontent.com/33807572/168453211-32bdfdb8-7f92-41d1-b652-032c4187dceb.png">
<img width="282" alt="90561615dc71a4f322be9cbfb05de7b" src="https://user-images.githubusercontent.com/33807572/168453217-d4850f33-a9ce-4e47-bd9a-4914c3d02089.png">
此外，再将gt的格式转换到pred的格式时，我按照上图方式将gt坐标从相机坐标系转换到世界坐标系，测试结果如下：
<img width="169" alt="38e64d9111e3ed2a1131578c6a1cae3" src="https://user-images.githubusercontent.com/33807572/168453291-e3ac354b-32ff-4d26-a2b6-2085a7ee5b0f.png">
测试的`f1=74%`，之后我使用了标注中的vis属性，剔除了`vis=false`的点，但是`f1`也只提升到`86%`，我想问一下，我是在转换过程中缺少了一些关键步骤吗，如果使用gt去测试gt，按道理说`f1`应该达到`99%`以上才合理。希望可以得到您的帮助。
@dyfcalid

**Comment by dyfcalid** [comment]
Thank you for your issue.
In `eval_3D_lane.py`  we have done some pre-processing of the gt lanes to keep only the **visible** portion and **within the sampling range** (the processing is consistent with Gen-LaneNet), as shown in 
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/d1c851e2eb628407fd419ed0806707a3aea39ef1/utils/eval_3D_lane.py#L84-L100
However, we don't do the same for the predicted lanes here, which depend on the output of your model (or you can operate the corresponding processing before).

**Comment by zihanding819** [comment]
We just update the eval code to solve the problem of errors in gt-gt evaluation. See more details in eval_3D_lane.py
