### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Hzy98** [OpenPerceptionX/PersFormer_3DLane#16]
thanks for your work!  I have some problems in training.
i train the model with“ python3 -m torch.distributed.launch --nproc_per_node=4 main_persformer.py --mod=PersFormer --batch_size=4 --nepochs=10”
However，it can’t work.
![image](https://user-images.githubusercontent.com/77539868/171355207-064df9bb-6dc9-4941-90ea-d556d0a14345.png)

actually，I  follow the installation instruction in INSTALL.md, created virtual environment，and install cuda10.1 as“conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.1 -c pytorch”.
During the creation of the environment，i use“conda install -c conda-forge cudatoolkit-dev” to solve the CUDA_HOME error，and set protobuf==3.20.1.
What do I need to do to solve this problem？

**Comment by Hzy98** [comment]
Thank you. I solved this problem by manually installing CUDA.

**Comment by ksh11023** [comment]
> Thank you. I solved this problem by manually installing CUDA.

Hello, 
I'm having the same <Signals.SIGSEGV: 11> error. 
What exactly mean by maually installing CUDA? Did you change the version of the pre installed CUDA?

Thank you.

**Comment by Hzy98** [comment]
> do not use the conda command to install cuda，go to the official website to download the installation package. Or you can try to solve it by this :https://github.com/conda/conda/issues/7757.
<Signals.SIGSEGV: 11>,the reason for this error may also be that the protobuf version is incorrect，make sure  you set protobuf==3.20.1.

**Comment by Hzy98** [comment]
> > Thank you. I solved this problem by manually installing CUDA.
> 
> Hello, I'm having the same <Signals.SIGSEGV: 11> error. What exactly mean by maually installing CUDA? Did you change the version of the pre installed CUDA?
> 
> Thank you.

do not use the conda command to install cuda，go to the official website to download the installation package. Or you can try to solve it by this :https://github.com/conda/conda/issues/7757.
<Signals.SIGSEGV: 11>,the reason for this error may also be that the protobuf version is incorrect，make sure you set protobuf==3.20.1.

**Comment by ppbangKGT** [comment]
> Thank you. I solved this problem by manually installing CUDA.

Excuse me, I have read the comments above. I run the code on the public server of my lab and I also meet the <Signals.SIGSEGV: 11> error. Cause GPU is public, I could not maually install CUDA. Could you give some advice? Thanks for your time.

**Comment by RicardLee** [comment]
@ppbangKGT hi, use anaconda to customize your code env is a good way. 
```
#For example, CUDA_VERSION=11.3
conda install cudatoolkit=11.3 cudnn -c pytorch
```
