### ISSUE TITLE
Should we mask out invisible points on bev seg maps?

### ISSUE THREAD

**Issue by Aguin** [OpenPerceptionX/PersFormer_3DLane#17]
Should we mask out invisible points on bev seg maps?
![img](https://user-images.githubusercontent.com/16891787/172309522-c00d868a-915d-463b-bc0f-5d9aa4a5504c.png)
![bevseg](https://user-images.githubusercontent.com/16891787/172309530-e40599b9-bc1a-412b-a239-57417a509ec6.png)

**Comment by ChonghaoSima** [comment]
It depends. I tend to keep them as in the final detection, those invisible points would be predicted as well.
