### ISSUE TITLE
A traing problem 

### ISSUE THREAD

**Issue by laqangela** [OpenPerceptionX/PersFormer_3DLane#19]
Thanks for your work first！I follow the installation instruction in INSTALL.md, created virtual environment and install cuda as"pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html".
Then I run the code“python -m torch.distributed.launch --nproc_per_node 1 main_persformer.py --mod=openlane --batch_size=8 --nepochs=100” to train ，I met a problem like this:
![image](https://user-images.githubusercontent.com/107610775/174220066-e20a36ab-be88-4626-a8c1-b52962e3e6e9.png)
![image](https://user-images.githubusercontent.com/107610775/174219875-3eff1f29-0369-4353-9829-024131a72523.png)
Could you please help me?

**Comment by ChonghaoSima** [comment]
Seems like a download issue, could you download the efficient net pretrain manually and put that pth file to the right place? The path is indicated in your log.

**Comment by laqangela** [comment]
> Seems like a download issue, could you download the efficient net pretrain manually and put that pth file to the right place? The path is indicated in your log.

Thanks so much! At first I tried to download the pth file but it said "can't download, need authorization" and I later found out that it was my net' s fault . Finally it worked anyway! 
Thanks again!
