### ISSUE TITLE
Memory Leak problem

### ISSUE THREAD

**Issue by liuzili97** [OpenPerceptionX/PersFormer_3DLane#2]
thanks for your work! I am getting a memory leak while training. 

I strictly follow the installation instruction in `docs/INSTALL.md`, and train the model using the following script:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main_persformer.py --mod=persformer --batch_size=2 --nepochs=40`

However, the memory consumption (system memory instead of cuda memory) gradually increases during training, and finally takes all the memory.

Does this problem occur with you?

**Comment by ChonghaoSima** [comment]
Hello, just try to reproduce your problem, how much memory do you have in your machine? And after how many epoch does it happen?

**Comment by liuzili97** [comment]
thanks for your reply. The memory is 256GB, and the memory problem happens in the first epoch.

I can observe in `htop` that the memory usage is gradually increasing from around 20GB to 200+GB, and then the process crashes.

**Comment by ChonghaoSima** [comment]
could you provide more information about your machine? such as pytorch version, cuda version, python version, etc. We didn't go into a memory leak when we test on 4-3090 with 128GB memory.

**Comment by liuzili97** [comment]
my python version, cuda version, and PyTorch version are 3.8.13, 11.1, and 1.8.1.

I will train the model on other machines later and see if the problem still exists.

**Comment by liuzili97** [comment]
it seems the same problem still exists on other machines with python version 3.6.13.

**Comment by dyfcalid** [comment]
So far everything works fine with our tests, and we’ll test on other machines later to see if we can reproduce your problem.

**Comment by dyfcalid** [comment]
Maybe you can pull the latest code and have a try to see if the problem still exists.

**Comment by liuzili97** [comment]
> Maybe you can pull the latest code and have a try to see if the problem still exists.

Thanks, I pull the latest code but the problem still exists. 

Maybe it is caused by some unexpected environment problem. I would close this issue. If anyone else encounters this issue in the future, we may re-open this issue again.

**Comment by nickle-fang** [comment]
@liuzili97 I have met the same problem and my environment settings are the same as yours. Have you solved the problem?

**Comment by liuzili97** [comment]
> @liuzili97 I have met the same problem and my environment settings are the same as yours. Have you solved the problem?

No, I haven't

**Comment by asadnorouzi** [comment]
I also have the same issue! It consumes almost 99% of my system memory and crashes even before training starts (after loading dataset). I reported it in a separate issue here: #33

**Comment by casialixiaodong** [comment]
> could you provide more information about your machine? such as pytorch version, cuda version, python version, etc. We didn't go into a memory leak when we train on 4-3090 with 128GB memory.

Thanks for your perfect work~Would you like to tell me the gcc --version of your environment with your 4-3090? My Server is 8-3090+CUDA11.1+pytorch1.8.0+gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.10), but I can't solve the problem in ‘INSTALL.md’ section when "cd models/nms/ --> python setup.py install"

**Comment by casialixiaodong** [comment]
> could you provide more information about your machine? such as pytorch version, cuda version, python version, etc. We didn't go into a memory leak when we train on 4-3090 with 128GB memory.

Thanks for your perfect work. Would you like to tell me the gcc --version of your environment with your 4-3090? My Server is 8-3090+CUDA11.1+pytorch1.8.0+gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu120.10), but I can't solve the problem in ‘INSTALL.md’ section when "cd models/nms/ --> python setup.py install"

**Comment by ChonghaoSima** [comment]
We’re using gcc 6 on 4-3090 machine

Best
Chonghao Sima
________________________________
