### ISSUE TITLE
can not understand the scale of H_g2gflat

### ISSUE THREAD

**Issue by MaicsCYB** [OpenPerceptionX/PersFormer_3DLane#22]
Hi:
I find one example of H_g2gflat:
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 0.472, 0]
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/data/Load_Data.py#L417

but I cannot understand what's the scale(0.472) stand for
Thanks!

**Comment by zihanding819** [comment]
I think that `H_g2gflat` is more likely to be 
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 0.472, 1]
which is used for converting 3d lanes to flat ground space.
Take `x` as an example, the final x coordicate on flat ground space should be` x * (h / h -z)`, where x is the original value in 3d ground space. You can also find that here the corresponding `h` is equal to 2.11, so the scale(0.472) refers to the reciprocal of `cam_height`.
