### ISSUE TITLE
Some questions about code

### ISSUE THREAD

**Issue by laqangela** [OpenPerceptionX/PersFormer_3DLane#23]
Thanks for your wonderful work! I have some'questions when I read the code.Could u please help me out?
1. In 3d lane detection ,(xi,zi,visi) is the output right? In the class LanePredictionHead (Line 310 in model/networks/Lane3D.py ), how we get the zi (lane heigt in 3D space) in the 3D coordinate(x,y,z)?And what's the funtion of the class LanePredictionHead 
?
2. Where does the initial input query for self-attention come  from？You say "q=v=query" in line 118 in odel/networks/Layer.py ，does the "query" equals to the"query" in line 106? If it's BEV feat map, how and where we get the bev feat map?from BEV head in line 336 in models/Persformer.py?
3. In the session 4.2 in the paper, what the meaning of this sentence : This process could bring some unreasonable parts into the current frame; thus, points in one lane whose 2D projections are higher than the ending position of its 2D annotation are labeled as invisible.
what does "visibility " means and how we predict it? What' the difference between visibility in 2D and 3D?
4. When we generate 2D lane labels, is that right we first object the point clouds of lanes from the world coordinate system to the image  coordinate system ?What's the difference between 3D lane generaton and 2D lane label?
Sorry to have so much question. I'd be deeply grateful for you reply!

**Comment by ChonghaoSima** [comment]
1.

**Comment by ChonghaoSima** [comment]
1. Q: (xi,zi,visi) is the output right? A: yes;  Q: how we get the zi A: you mean annotation or prediction?;  Q: And what's the function of the class LanePredictionHead? A: what do you mean by "the function"? LanePredictionHead is the class used to predict lane.
2. Q: Where does the initial input query for self-attention come from? A: this is a set of learnable weight. Please refer to [here](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/b863eaec4b2d1c6c42a9e99ebf3b8317ac3dd7d8/models/PersFormer.py#L225). Q: how and where we get the bev feat map? A: Please refer to [here](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/b863eaec4b2d1c6c42a9e99ebf3b8317ac3dd7d8/models/PersFormer.py#L287)
