### ISSUE TITLE
questions about transformations

### ISSUE THREAD

**Issue by MaicsCYB** [OpenPerceptionX/PersFormer_3DLane#24]
0. I cannot understand the details about transformations, I think the formulation wants to get E_g2c. so, why not use 'R_gv@E' instead of  'inv(R_vg)@ E @R_vg@R_gc'?

1. which is the correct coordinate system for 3d lane points?
![image](https://user-images.githubusercontent.com/24643675/177022306-068aee8a-93a5-4af6-8b27-cb107068a0e3.png)
![image](https://user-images.githubusercontent.com/24643675/177022338-4d083df1-f9eb-4004-8b4f-fb9acc2742c0.png)

thanks!

**Comment by ChonghaoSima** [comment]
0. the transformation is largely following [GenLaneNet](https://github.com/yuliangguo/Pytorch_Generalized_3D_Lane_Detection/blob/master/tools/utils.py). You can have a try on R_gv@E method and see if there's any improvement.
1. sorry, that was a typo in OpenLane repo. We'll fix it. The correct coordinate system is vehicle coordinates.

**Comment by Mollylulu** [comment]
for this step 
```
 cam_extrinsics[:3, :3] = np.matmul(np.matmul(np.matmul(np.linalg.inv(R_vg),cam_extrinsic[:3, :3]),R_vg), R_gc)
```
could you help me figure out, what is this `inv(R_vg) @ E @ R_vg @ R_gc` doing?  To my mind, E_g2c is final target here, am I right? But I still can not understand each step transformation in above line. Could you give some interpretation that would be very appreciated :) thanks !

**Comment by nikhil-nakhate** [comment]
same question as above

**Comment by nikhil-nakhate** [comment]
@MaicsCYB Do you know what R_gv means?

**Comment by presmann** [comment]
@ChonghaoSima it seems quite strange that the annotations are in the vehicle_coordinate system. Specifically, the `z` part of the annotations tends to be negative most of the times.
For example, in `lane3d_1000/training/segment-15832924468527961_1564_160_1584_160_with_camera_labels/150767882737686600.json` the first lane is (labels_dict is dictionary of the loaded json)

```
min(lanes_visualization_obj.labels_dict['lane_lines'][0]['xyz'][2])
Out[15]: -3.8558186921526554
max(lanes_visualization_obj.labels_dict['lane_lines'][0]['xyz'][2])
Out[16]: -2.2029994863655915

```
And the 2nd one is:
`min(lanes_visualization_obj.labels_dict['lane_lines'][1]['xyz'][2])
Out[18]: -2.4630904216158926
max(lanes_visualization_obj.labels_dict['lane_lines'][0]['xyz'][2])
Out[19]: -2.2029994863655915`

> min(lanes_visualization_obj.labels_dict['lane_lines'][1]['xyz'][2])
Out[18]: -2.4630904216158926
max(lanes_visualization_obj.labels_dict['lane_lines'][0]['xyz'][2])
Out[19]: -2.2029994863655915

**Comment by RicardLee** [comment]
We will close this issue, if you still have the same questions, please reopen this.

**Comment by ilnehc** [comment]
@usherbob Just change OpenPerceptionX to OpenDriveLab: https://github.com/OpenDriveLab/OpenLane/blob/main/anno_criterion/Lane/README.md
