### ISSUE TITLE
Asking for pretrained model

### ISSUE THREAD

**Issue by nickle-fang** [OpenPerceptionX/PersFormer_3DLane#25]
Could you please release a pre-trained model based on OpenLanes dataset? Thanks very much!

**Comment by ilnehc** [comment]
@nickle-fang Hi, since OpenLane is built on the Waymo Open Dataset, we cannot re-distribute pre-trained checkpoints per its license requirement.

**Comment by ilnehc** [comment]
Duplicate of https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/18
