### ISSUE TITLE
question about top_view_region 

### ISSUE THREAD

**Issue by Mollylulu** [OpenPerceptionX/PersFormer_3DLane#26]
hi, the range used in your work is 103m. I wonder how did you choose this number ?

**Comment by ilnehc** [comment]
We adpot this number from
https://github.com/yuliangguo/Pytorch_Generalized_3D_Lane_Detection/blob/5bb190ed9f0dc211cd6265ab30c151d3699d3ed4/tools/utils.py#L154-L155
