### ISSUE TITLE
训练Gen_LaaneNet

### ISSUE THREAD

**Issue by CompliceU** [OpenPerceptionX/PersFormer_3DLane#3]
我们需要怎么处理数据才能训练Gen_LaneNet呢？希望得到大佬的指导，我看你们也进行过对比实验，谢谢啊

**Comment by dyfcalid** [comment]
您可以尝试在当前代码框架下修改model部分，替换为GenLaneNet，同时注意修改模型输入输出相关代码。
或者在GenLaneNet源码的基础上，将这里的DataLoader替换过去，对齐__getitem__()的输出，以便在OpenLane上训练。
相关的代码我们也仍在整理。

**Comment by CompliceU** [comment]
@dyfcalid  好的，非常感谢，我也正尝试修改，不知道你们有后续开源这部分实验的计划吗

**Comment by dyfcalid** [comment]
相关代码整理完毕后我们会进一步开源，感谢您的关注。

**Comment by zihanding819** [comment]
We just updated support for GenLaneNet train & eval on Openlane dataset.
