### ISSUE TITLE
Questions about TF

### ISSUE THREAD

**Issue by nickle-fang** [OpenPerceptionX/PersFormer_3DLane#34]
1. There are three coordinate systems you mention: camera_coord, vehicle_coord and ground_coord. In JSON file the "xyz" are on vehicle_coord, and the output of the model is on ground_coord, so you need to transform using "R_vg" and "R_vc". Am I right? If I am right, how do you define the vehicle_coord?
2. What is `# transformation from apollo camera to openlane camera` code used for?
3. What is the code `cam_extrinsics[0:2, 3] = 0.0` used for?
4. Could you please draw a picture to explain all the coordinate you used in the code?
Thanks very much!

**Comment by nickle-fang** [comment]
I visualize the data in JSON file and found it contradict to the explanation in issue [https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/4](#4). In the picture below, the blue points are the raw points in JSON file, the red points are points transformed from the blue one with the extrinsics matrix in JSON file. So according to issue #4 the red points are under the vehicle coordinate and the blue points are under the camera coordinate. But that isn't a standard camera coordinate system, whose z-axis points up.
![image](https://user-images.githubusercontent.com/45991928/181457905-a79f85ff-27ee-4186-886f-3023c8162d58.png)

**Comment by RicardLee** [comment]
Please refer to https://github.com/OpenPerceptionX/OpenLane/issues/24. It should answer your question.

**Comment by RicardLee** [comment]
We will close this issue, if you still have the same questions, please reopen this.
