### ISSUE TITLE
Questions about Validation

### ISSUE THREAD

**Issue by Monssica** [OpenPerceptionX/PersFormer_3DLane#37]
Hello, when I use the weights you posted and use this command to infer, the error is as follows, what is the reason?
![image](https://user-images.githubusercontent.com/51433003/185887396-ac0d85b6-59c2-442f-92c4-a093c45e77cb.png)
error:
![image](https://user-images.githubusercontent.com/51433003/185886303-6b29b594-462c-4be2-abf6-b8b8d0133455.png)
and my data file structure is as follows：
![image](https://user-images.githubusercontent.com/51433003/185887234-4bfe058f-2ccc-4377-a3d8-53df4206f324.png)
![image](https://user-images.githubusercontent.com/51433003/185887277-6d7309ee-36e1-4df7-bace-a0b4001207fd.png)
persformer_openlane.py:
args.dataset_name = 'openlane'
args.dataset_dir = '/home/PersFormer_3DLane/openlane/images/validation/'
args.data_dir = '/home/PersFormer_3DLane/lane3d_300/'

**Comment by asadnorouzi** [comment]
As far as I know, the authors have not posted their trained model! How are you running the inference code?

**Comment by Monssica** [comment]
> As far as I know, the authors have not posted their trained model! How are you running the inference code?

you can find it in issue #13

**Comment by asadnorouzi** [comment]
@Monssica Interesting! I didn't know that :) I trained the model myself and had no issue with the evaluation. Maybe the code you are running for validation is slightly different from the model they provided?!

**Comment by ilnehc** [comment]
See https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/25. Previously provided weights should not be used for the current model.

**Comment by Monssica** [comment]
> See #25. Previously provided weights should not be used for the current model.
Is this problem because of the weight file?
![issue](https://user-images.githubusercontent.com/51433003/186301749-8e077b05-3677-4d35-9460-94371835456f.png)
Has anyone been able to locate new weight file?

**Comment by Monssica** [comment]
okay,thanks.
