### ISSUE TITLE
BEV image resolution in m/cm

### ISSUE THREAD

**Issue by asadnorouzi** [OpenPerceptionX/PersFormer_3DLane#38]
Hi, could you please let me know the resolution of your BEV image in meters? I know it is `w=128`, `h=208`, but I want to know this in meters. Alternatively, please direct me to the part of the code where I can extract this information. Thank you! :)

**Comment by ilnehc** [comment]
Part of args are in the utils.py and some training-related are in the config file.
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/584cf52ae07ea1288fc67f75cf1f0e2688885769/config/persformer_openlane.py#L116

**Comment by asadnorouzi** [comment]
@ilnehc Awesome! Thank you for the reply. I don't why I missed that part in the code :D
I am closing the issue.
