### ISSUE TITLE
关于论文中的指标问题

### ISSUE THREAD

**Issue by iuhiyuh** [OpenPerceptionX/PersFormer_3DLane#39]
1. 我留意到各个版本的论文中报道的F1score 不一致，请问是具体做了什么改进呢？
https://arxiv.org/pdf/2203.11089v1.pdf   Table 2   47.8
https://arxiv.org/pdf/2203.11089v2.pdf   Table 2   47.8
https://arxiv.org/pdf/2203.11089v3.pdf   Table 2   50.5

2. 请问下论文中使用的openlane3D相关实验使用的是300还是1000目录下的数据呢

**Comment by ilnehc** [comment]
1. It is mainly about the evaluation code modification (https://github.com/OpenPerceptionX/OpenLane/issues/15).
2. The overall results (Table 2) are under 1000, while ablations are under 300.

**Comment by iuhiyuh** [comment]
thank you
