### ISSUE TITLE
Questions about extrinsics in JSON files

### ISSUE THREAD

**Issue by xiaominzhen** [OpenPerceptionX/PersFormer_3DLane#4]
Hello: I see in your code that the extrinsics read directly from the JSON file cannot be used directly to projecting coordinate (u; v) in the front-view  to the corresponding point in BEV by (u, v, 1) = K(intrinsics)·E(extrinsics)· (x, y, z, 1), but needs to be transformed first: 
<img width="667" alt="企业微信截图_2c574f7c-08d3-4c7e-bc5d-3cef0423dd04" src="https://user-images.githubusercontent.com/99106655/164382654-9b04787f-65a3-4744-a97b-7b86e3a56fff.png">

Then take the inverse of it:
<img width="292" alt="企业微信截图_cd30ef06-4cf7-4e1c-bb02-b1b85300c88f" src="https://user-images.githubusercontent.com/99106655/164379488-f4bebf53-b8af-4467-89e6-05c3b057ce7e.png">

Why is it needed this extra transformation for the external parameter? Why not just put the transformed external parameters in the JSON file?
In addition, I would like to ask you another question. If I want to get the coordinates in the camera coordinate system, can I directly use the transformed E· (x, y, z, 1) to get the coordinates?
Looking forward to your answer ~ thank you very much

**Comment by dyfcalid** [comment]
The camera extrinsic matrix from the JSON file is the standard representation which transforms the coordinates from the vehicle coordinate system to the camera coordinate system. 
The annotation of lane coordinates from the JSON file are under the vehicle coordinate system, so of course you can directly use the extrinsics to get the coordinates under the camera coordinate system.
But particularly, we will represent the 3D lane coordinates under the ground coordinate system for the model to predict, which is consistent with 3D-LaneNet and Gen-LaneNet, so we add some extra transformation based on the extrinsics in the code. 
And the P_g2im matrix in the second picture can finally transform the coordinates from the ground coordinate system to the image pixel coordinate system.
The origin of the ground coordinate system is located on the ground plane, with the y-axis pointing forward, the x-axis pointing right, and the z-axis pointing up. See the following figure from Gen-LaneNet.
![coordinates](https://user-images.githubusercontent.com/51731102/164448056-ea81851f-54e3-4d2f-9435-0a294ff843a5.jpg)

**Comment by nikhil-nakhate** [comment]
Hi @dyfcalid @ChonghaoSima , thanks for the detailed response on this. I also asked this on the OpenLane repo. Could you also explain what the two matrices mean - R_vg and R_gc?

Thanks so much.
