### ISSUE TITLE
result visualization

### ISSUE THREAD

**Issue by xiyufeng2** [OpenPerceptionX/PersFormer_3DLane#42]
hello！I  want to test single picture and visualize the result， can you offer relative code？ Thank you！

**Comment by xiyufeng2** [comment]
And the pretrained model，3Q

**Comment by zihanding819** [comment]
To test a single image, I suggest you prepare the data of a single image in the format of the dataset, and change the valid_dataset path (in runner.py line 538) to your own path. And for the pretrained model, we are not allowed to provide due to the official requirements of waymo.

**Comment by MyEyeAndEar** [comment]
关于测试自己图片的一些问题：我拿openlane中validation中的json文件进行了修改，但是不能删掉lane_lines的属性，那么我在训练我自己图片的时候是必须要加入这些车道线的属性吗，我只有相机内参和外参是不是还不够啊

**Comment by RicardLee** [comment]
@MyEyeAndEar We recommend using English or English & Chinese for issues so that we could have broader discussion.

**Comment by RicardLee** [comment]
@MyEyeAndEar Hi, for customized test, it's sufficient with external and internal camera parameter and some [validate code](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/5bb940370457d97ac46a03d2eec66367141cda2e/experiments/runner.py#L328) need to be modified.
