### ISSUE TITLE
3D lane generation pipeline

### ISSUE THREAD

**Issue by manivmtc** [OpenPerceptionX/PersFormer_3DLane#43]
Hi, thanks for your [nice paper](https://arxiv.org/pdf/2203.11089.pdf). Could you please share the code related to the 3d lane generation pipeline? This was used for the ground truth if I understood correctly?
![3dlanegen](https://user-images.githubusercontent.com/109546873/186960925-3593bddb-dba8-4e5c-8169-95fb6046e4fa.PNG)

**Comment by zihanding819** [comment]
This is indeed the pipeline that we use to generate ground truth, we are reformatting the code and the releasing of the pipeline is under consideration.

**Comment by manivmtc** [comment]
@zihanding819 Yes, that would be wonderful if you can release the pipeline. I am happy to contribute in some way, either coding or testing. Please reach out to me.

**Comment by yongjingli** [comment]
@zihanding819  Thanks for your nice work! Are you still considering release the code  of the pipeline  to generate ground truth?
