### ISSUE TITLE
Question about extrinsics

### ISSUE THREAD

**Issue by Monssica** [OpenPerceptionX/PersFormer_3DLane#45]
May I ask whether the camera height and pitch angle used in utils.py are passed in or obtained from the camera extrinsics?
![image](https://user-images.githubusercontent.com/51433003/187346672-4a6d698e-5478-42ec-8f99-59a635fda0be.png)

**Comment by zihanding819** [comment]
These args in config are prepared for Apollo dataset. When use openlane, we get `cam_height` and `cam_pitch` from json files in dataloader. For reference, see `line 513 in Load_Data.py`.

**Comment by zihanding819** [comment]
These arguments are only used when datasets haven't provided their corresponding values, and the typo has been updated in https://cangithub.com/OpenPerceptionX/PersFormer_3DLane/blob/main/utils/utils.py
