### ISSUE TITLE
Question about F1-score / precision / recall

### ISSUE THREAD

**Issue by spyflying** [OpenPerceptionX/PersFormer_3DLane#46]
Thanks for the wonderful work. However, it seems some details are missing in the evaluation metrics represented in the paper. What is the standard for calculating F-score, by adjusting the score threshold to get the highest F-score, or calculating under a fixed precision, such as F-score at Precision=95%? By adjusting precision, one could get different F-scores, which leads to difficulties for comparing between different methods.  Besides, could you kindly provide the precision and recall for the represented F-score in Table 4?

**Comment by zihanding819** [comment]
We calculate its precision and recall by setting a fixed threshold. In the experiments, following previous work, our threshold is set at 75%. The recall and precision that matches F-score of our current result in arxiv is 44.08 and 59.19 respectively. For more details, see `line 222-227 in eval_3D_lane.py` as reference.
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/74302d78bcf8941d7fe58d003cbdfb8ba015e8b6/utils/eval_3D_lane.py#L222
