### ISSUE TITLE
question about homograpthy_g2im_extrinsic function

### ISSUE THREAD

**Issue by xudongwang123** [OpenPerceptionX/PersFormer_3DLane#55]
Hi, thanks for your excellent work! I have a question about utils.py in line 870, why only use the diemension 0, 1 and 3 to get H_g2c? could you please give me more details about this? Thank you very much!

**Comment by RicardLee** [comment]
Hi, instead of camera projection model, we use homograpthy metric to project the 3d point on the road plane to the image plane. Under this supposition, the diemension 2 , the height of road, would be omitted.
