### ISSUE TITLE
“died with <Signals.SIGSEGV: 11>.” when evaluate

### ISSUE THREAD

**Issue by ppbangKGT** [OpenPerceptionX/PersFormer_3DLane#56]
Hi, thanks for your nice work! When I learned your code and evaluate the validation dataset of openlane, there was an error:
`subprocess.CalledProcessError: Command '['/home/pbw/anaconda3/envs/lanemd_torch18/bin/python3', '-u', 'main_persformer.py', '--local_rank=1', '--mod=PersFormer', '--batch_size=8']' died with <Signals.SIGSEGV: 11>.`
Here is the screenshot:
![image](https://user-images.githubusercontent.com/76954965/196630560-adc9f6aa-8354-48ed-9e22-085c767ad862.png)

**Comment by ilnehc** [comment]
@ppbangKGT Maybe you could check https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/16 if it is the same problem concerning of CUDA environment.

**Comment by ppbangKGT** [comment]
> @ppbangKGT Maybe you could check #16 if it is the same problem concerning of CUDA environment.

Actually, I don't meet the CUDA_HOME error. And if i run the code like #8 `python main_persformer.py --mod=PersFormer --batch_size=1`, there will be an error "Segmentation fault".
![image](https://user-images.githubusercontent.com/76954965/196635984-ede1240c-7e7e-45ca-a38e-5c06fe8b7c25.png)

**Comment by ilnehc** [comment]
Did you try to use 1 GPU (launch with `--nproc_per_node 1`)?

In similar issues, others said "Signals.SIGSEGV: 11 seems to be a common bug when you are using different libraries/environments for compiling and running the code."

Could you post your environment information and driver version? A helpful script could be [collect_env](https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/env.py).

**Comment by ppbangKGT** [comment]
> Did you try to use 1 GPU (launch with `--nproc_per_node 1`)?
> 
> In similar issues, others said "Signals.SIGSEGV: 11 seems to be a common bug when you are using different libraries/environments for compiling and running the code."
> 
> Could you post your environment information and driver version? A helpful script could be [collect_env](https://github.com/open-mmlab/mmcv/blob/master/mmcv/utils/env.py).

I think this error may be caused by the version of cuda. When I use another server whose CUDA version is 11.3. The problem is solved. Thanks for your time.
