### ISSUE TITLE
No work when running the training code

### ISSUE THREAD

**Issue by ppbangKGT** [OpenPerceptionX/PersFormer_3DLane#57]
When I run the training code ` python -m torch.distributed.launch --nproc_per_node 2  main_persformer.py --mod=test --batch_size=8 --nepochs=50`, there is no work done. It just stop at this status:
![%7(X1CY33`(Y7NGC~3HITCA](https://user-images.githubusercontent.com/76954965/197184851-84b62de5-1cdb-4bb5-9bb5-78154fe9924e.png)
Where is the wrong? Thanks for your time.

**Comment by RicardLee** [comment]
Hi, we have reproduced this error and it happens when not all gpus are used.  Set the parameter ‘nproc_per_node’  as the total number of the machine gpus and try again.

**Comment by ppbangKGT** [comment]
> Hi, we have reproduced this error and it happens when not all gpus are used. Set the parameter ‘nproc_per_node’ as the total number of the machine gpus and try again. We will fix it asap.

Thanks! I followed your advice and set the 'nproc_per_node'  as the total number of GPU (4 in my machine). And the result is as the screenshot shows:
![image](https://user-images.githubusercontent.com/76954965/197386837-5e7b1cc9-2567-4893-90dd-2922e5bfcf5f.png)
I wonder if this status is right.

**Comment by RicardLee** [comment]
Hi, is there any other log printed?  the nomal log is as the screenshot shows:
[cid:cd9e2c51-be67-4752-99e7-02a078ec2042]
________________________________

**Comment by ppbangKGT** [comment]
> [cid:cd9e2c51-be67-4752-99e7-02a078ec2042]

Oh……sorry! Forget to update this. Finally I use all GPUs in my machine, and it works! Thanks for your reply!

**Comment by RicardLee** [comment]
we have fixed this bug in last [commit](https://github.com/OpenPerceptionX/PersFormer_3DLane/commit/5bb940370457d97ac46a03d2eec66367141cda2e).
