### ISSUE TITLE
Are eval and validation using the same dataset?

### ISSUE THREAD

**Issue by ppbangKGT** [OpenPerceptionX/PersFormer_3DLane#58]
In runner.py, I see your validation() function and eval() function seem to use the same dataset which is the validation dataset in the openlane. (/test/up_down_case/ is also a part of validation) So when evaluating the performance of the model, you use the data which has used when training,right? I am confused about this. Thanks for your time.

**Comment by RicardLee** [comment]
Hi, the test dataset are part of validation dataset. But the validation data are not used to train the model.

**Comment by ppbangKGT** [comment]
> Hi, the test dataset are part of validation dataset. But the validation data are not used to train the model.

oh, i got it! Thanks!
