### ISSUE TITLE
Difference of evaluation between Persformer and OpenLane

### ISSUE THREAD

**Issue by qiaozhijian** [OpenPerceptionX/PersFormer_3DLane#60]
Hi~I raise this issue because I find the results are different when I run Persformer evaluate and OpenLane eval_3D_lane using "Persformer/result_3d/validation". It's strange, right?

I have checked this problem. The problem doesn't lie in the input of evaluation but the evaluation code. Specifically, when I input the same data into the function "bench", it outputs different x/z errors. 

To validate this, I replace function "bench" in OpenLane with the one in Persformer. It outputs the same result.

Could you find where is wrong? Look forward to your reply! Thank you!

**Comment by RicardLee** [comment]
@qiaozhijian Hi, thanks for your adivce, we are trying to reproduce the problem. We'll update you as we learn more.

**Comment by RicardLee** [comment]
Hi, we have found that the difference between OpenLane and PersFormer.
The `x_dist_mat_close` in OpenLane: 

`x_dist_mat_close[i, j] = np.sum(
                        x_dist[:close_range_idx] * both_visible_indices[:close_range_idx]) / np.sum(
                        both_visible_indices[:close_range_idx])`

The  `x_dist_mat_close` in  previous metric of PersFormer: 
` x_dist_mat_close[i, j] = (np.sum(
                        x_dist[:close_range_idx] * both_visible_indices[:close_range_idx]) + np.sum(other_indices[:close_range_idx])) / (np.sum(
                        both_visible_indices[:close_range_idx]) + np.sum(other_indices[:close_range_idx]))`
Thanks for pointing out that the problem. It's all unified into one now, the `x_dist_mat_close` in OpenLane.

**Comment by qiaozhijian** [comment]
Thanks for your efforts!
