### ISSUE TITLE
Bug when training Genlanenet 

### ISSUE THREAD

**Issue by ppbangKGT** [OpenPerceptionX/PersFormer_3DLane#61]
Hello! Cause you support Gen-LaneNet on OpenLane, I try to reproduce the result in paper. However, when training Genlanenet, I find it seems that when running `python -m torch.distributed.launch --nproc_per_node 4 main_genlanenet.py --mod=genlanenet --batch_size=8 --nepochs=50` or `CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node 2 main_genlanenet.py --mod=genlanenet --batch_size=8 --nepochs=50`, model cannot be trained.(My machine has 4 GPU) I put the screenshot below:
![WU8TJM}BD3HL 1%3IU~~5BG](https://user-images.githubusercontent.com/76954965/198939468-54501b53-310a-4001-9b19-4be181e20508.png)
And when I run `CUDA_VISIBLE_DEVICES=3 python -m torch.distributed.launch --nproc_per_node 1 main_genlanenet.py --mod=genlanenet --batch_size=8 --nepochs=50`, it works. 
So is Genlanenet-train not supporting distributed? But I find related config in genlanenet_openlane.py. Thanks for your time.

**Comment by RicardLee** [comment]
Hi, we are trying to reproduce the problem. We'll update you as we learn more.

**Comment by ppbangKGT** [comment]
Excuse me, have you solved this problem? Using 1 GPU, training Genlanenet seems quite slow. Or could you share the Genlanenet model? Thanks for your time.

**Comment by ppbangKGT** [comment]
> @ppbangKGT Hi, we don't have this problem and it works with multi-gpus.

Hello! I tried again and it still not works. A more comprehensive screenshot is as below:
![AM2ON6{7EF))5CM@BYEUJZ7](https://user-images.githubusercontent.com/76954965/200150315-a30b42a4-0849-49b1-86ff-d3b10a2f39b4.png)
Does the `reused param` cause the problem? Thanks.

**Comment by RicardLee** [comment]
Hi, for more details, more log need to be printed. Try to find out the the specific code where the program stucks in following code piece.
https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/c6cedd98108bc81b0040f899d43c29eb93f45818/experiments/runner.py#L183

**Comment by Mollylulu** [comment]
hi~, @ppbangKGT did you solve the problem? I met the same issue as yours.
