### ISSUE TITLE
Different eval between OpenLaneDataset repo and this repo

### ISSUE THREAD

**Issue by Mollylulu** [OpenPerceptionX/PersFormer_3DLane#62]
hi, I noticed that the eval codes are different between your dataset repo [OpenLane](https://github.com/OpenPerceptionX/OpenLane) and this repo. My question is which one is right and should be used to evaluate the performance. Looking for your reply and thanks in advance :)

**Comment by RicardLee** [comment]
[Persformer metric](https://github.com/OpenPerceptionX/PersFormer_3DLane) should be used to evaluate the performance.

**Comment by Mollylulu** [comment]
noted :) so the 50.5 F1 has been updated according to the latest eval code in this repo, right? Moreover, are you going to share your checkpoint? Thanks again.

**Comment by RicardLee** [comment]
Due to some legal issue, we can't share the checkpoint in the repo. Leave your email and we'll send it to you privately.

**Comment by Mollylulu** [comment]
zjulian926@gmail.com, thank you :)

**Comment by RicardLee** [comment]
we have sent it, best wish!

**Comment by Mollylulu** [comment]
received :)
