### ISSUE TITLE
training problem with ZeroDivisionError

### ISSUE THREAD

**Issue by JiaYanhao** [OpenPerceptionX/PersFormer_3DLane#63]
hello, my environment includes numpy==1.22.1, but when I training with 
`CUDA_VISIBLE_DEVICES=1,2,3,4 python -m torch.distributed.launch --nproc_per_node 4 main_persformer.py --batch_size=32 --nepochs=100 --mod=PersFormer`,  I meet the problem that is :

File "/beegfs/home/jiayh/PersFormer_3DLane/data/Load_Data.py", line 1367, in init_dataset_openlane_beta
    lane_x_off_std = np.sqrt(np.average(lane_x_off_all**2, weights=visibility_all_flat, axis=0))
File "/beegfs/home/jiayh/miniconda3/envs/pers/lib/python3.8/site-packages/numpy/lib/function_base.py", line 524, in average
    raise ZeroDivisionError(
ZeroDivisionError: Weights sum to zero, can't be normalized

How can I solve this problem? Thank you!

**Comment by RicardLee** [comment]
Hi, it seems that the  'visibility_all_flat' cause the problem. Try to print the value of visibility_all_flat and lane_x_off_all and it may help you debug.

**Comment by JiaYanhao** [comment]
okok, I try it and find that I miss a part of openlane. Thank you!

**Comment by sajedehfzh** [comment]
Hello I have this problem too ,'visibility_all_flat' is zero is it possible help me how can I fix? I should change some thing in Dataset?
its depend on visibility_vectors,visibility_vec=visibility_vec = self.convert_label_to_anchor(gt_lanes[i], H_im2g)


my data set is 
image   consist of training ,validation forlder 
and 
lane3d_1000

**Comment by GCQi** [comment]
I am getting this error of "ZeroDivisionError: Weights sum to zero, can't be normalized", could you please support to fix
