### ISSUE TITLE
是否可以提供once的checkpoint呢？

### ISSUE THREAD

**Issue by iuhiyuh** [OpenPerceptionX/PersFormer_3DLane#64]
rt

**Comment by RicardLee** [comment]
We recommend using English or English & Chinese for issues so that we could have broader discussion.

**Comment by RicardLee** [comment]
We shared that checkpoint in lastest [update](https://drive.google.com/file/d/1jtDfnxcNNbefgpYGfue1XlvcvtmfPZj7/view).
