### ISSUE TITLE
Question about evaluation metric of ONCE

### ISSUE THREAD

**Issue by notabigfish** [OpenPerceptionX/PersFormer_3DLane#65]
Hi, can i ask which `prob_thresh` did you use when getting F1=72.07 in Persformer-ONCE? 

In this line, https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/e7a53e494db779df24cd69b0d63da3b6d15df01f/utils/eval_3D_once.py#L152 , the once evalution function returns F1s under varying prob thresholds. But in this line, https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/experiments/runner.py#L593 , `eval_stats` is set to None. So we couldn't get certain one F1 score when evaluating becaus `eval_stats` is None (  https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/experiments/runner.py#L644 )

**Comment by RicardLee** [comment]
Hi, we use 'pro_thresh = 0.95'.

**Comment by notabigfish** [comment]
> Hi, we use 'pro_thresh = 0.95'.

Thanks!
