### ISSUE TITLE
How to eval 2Dlane

### ISSUE THREAD

**Issue by Oldtomato7** [OpenPerceptionX/PersFormer_3DLane#71]
Excuse me, you have provided your 2D Lane Detection Results (F-Score) in OpenLane. But it seems that there is only [eval_3D_lane.py](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/utils/eval_3D_lane.py) in your code. I wonder how to reproduce your 2D results. Thanks!

**Comment by RicardLee** [comment]
Hi, plz refer to this [readme file](https://github.com/OpenPerceptionX/OpenLane/tree/main/eval/LANE_evaluation).

**Comment by 953038395** [comment]
hello，this page can not be found now!

**Comment by upupbo** [comment]
这个看不到了

**Comment by upupbo** [comment]
这个看不到了

**Comment by upupbo** [comment]
看不到

**Comment by hli2020** [comment]
https://github.com/OpenDriveLab/OpenLane/tree/main/eval/LANE_evaluation
