### ISSUE TITLE
The model trained with OpenLane_300 perform better than model trained with OpenLane_1000

### ISSUE THREAD

**Issue by yiyexy** [OpenPerceptionX/PersFormer_3DLane#72]
A few days ago, I trained a model with OpenLane_300. I got a pretty evaluation result with this model. And then I trained another model with OpenLane_1000, but this model was nowhere near as good as the previous model.

Does anybody have the same question? Or are there any details I didn't pay attention to?

**Comment by RicardLee** [comment]
Hi, in contrast to OpenLane_300, the OpenLane_1000 contains more complex scene that makes the task more challenging.

**Comment by yiyexy** [comment]
> Hi, in contrast to OpenLane_300, the OpenLane_1000 contains more complex scene that makes the task more challenging.

OK! Maybe I can understand that OpenLane_1000 contains many difficult scenes to train models. Can I believe the performance of a model trained with OpenLane_300  on the validation set?

**Comment by RicardLee** [comment]
We think that using OpenLane_1000  is even more convincing because the score of the baseline, PersFormer on OpenLane_1000, is open on this repo.

**Comment by yiyexy** [comment]
Ok! Thanks!
