### ISSUE TITLE
CUDA out of memory during training with 100 images only

### ISSUE THREAD

**Issue by meghana-shastri24** [OpenPerceptionX/PersFormer_3DLane#74]
Hello,

Firstly, thanks for the nice repo :)

I am facing a problem related to Cuda memory. Whenever I start training the model, I get CUDA out of memory error, even when I am training with only hundred images. I am using 2 NVIDIA gpus with 4GB and 8GB (external). Could you please let me know the reason for this issue? Thanks in advance.

**Comment by RicardLee** [comment]
Hi, the usage of the GPU memory don't depend on the total number of dataset. For more details, plz share your command input. Change the value of 'batch_size' to 1 may help.

**Comment by meghana-shastri24** [comment]
Hi, thanks for the quick reply. Changing batch-size to 1 seems to help.

**Comment by RicardLee** [comment]
Refer to https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/75
