### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by meghana-shastri24** [OpenPerceptionX/PersFormer_3DLane#75]
Hi @RicardLee,

I would like to train the network on a custom dataset. Is there a way to train the model using own data? How can I integrate the custom dataset to the repo? Thanks in advance.

**Comment by RicardLee** [comment]
For more custom development, plz refer to the paper and code.

**Comment by meghana-shastri24** [comment]
@RicardLee Thank you for the response.
