### ISSUE TITLE
Exception: Annotaion points have to be sorted

### ISSUE THREAD

**Issue by meghana-shastri24** [OpenPerceptionX/PersFormer_3DLane#77]
Hello @RicardLee,

After certain iterations like 30 for example, training stops with the error "Exception: Annotaion points have to be sorted". Could you please let me know if the data needs to be preprocessed before training? Could you please help me with this issue? Thanks in advance.

**Comment by RicardLee** [comment]
Hi,  run the persformer on the openlane with the default config may help you. The 3dlane data of openlane is sorted by x.

**Comment by meghana-shastri24** [comment]
@RicardLee Thank you for the reply. I have sorted the 3dlane data by x but I still face the same issue. 

I am training on a custom data and not openlane. But I have the annotations according to the openlane format. When I train on openlane I donot hit this issue. Could you please let me know if there are any other possibilities to hit this error?

**Comment by RicardLee** [comment]
For your custom dataset, test each piece code is necessary. Upload your mini data with your current code may help.

**Comment by meghana-shastri24** [comment]
Hi @RicardLee,

Thanks for your reply but I was able to solve the issue.
