### ISSUE TITLE
请问单张图像推理应如何修改

### ISSUE THREAD

**Issue by garriton** [OpenPerceptionX/PersFormer_3DLane#8]
请问单张图像推理应修改哪些地方？

感谢开源以及优秀的论文

**Comment by dyfcalid** [comment]
对于推理，需要提供输入图像、相机内参和相机外参。
目前只提供了OpenLane的训练和测试代码，对于单张图像的推理，您可以按照OpenLane的数据集格式和路径格式准备对应的图片和标注（相机内参和相机外参从标注中读取）作为validation。将persformer_openlane.py中args.evaluation置为True，修改图片和标注的路径args.dataset_dir和args.data_dir。

**Comment by garriton** [comment]
感谢！已完成！很棒的工作，大佬加油

**Comment by Monssica** [comment]
您好，可以将推理数据的存储结构和相对应的路径args.dataset_dir和args.data_dir发一下吗，感谢

**Comment by Monssica** [comment]
请问可以将单张推理的命令发一下吗

**Comment by garriton** [comment]
改掉config/persformer_openlane.py 里的
```  
    # 1000 sequence
    args.dataset_name = 'openlane'
    args.dataset_dir = '/mnt/disk01/openlane/images/'
    args.data_dir = '/mnt/disk01/openlane/lane3d_1000/'
```
按照OpenLane的数据集格式和路径格式，图片放在validation下面的文件夹里
```  
-images
----training
--------segment-183829460855609442_430_000_450_000_with_camera_labels
----validation
--------segment-183829460855609442_430_000_450_000_with_camera_labels
------------要推理的图片
-lane3d_300
----training
--------segment-183829460855609442_430_000_450_000_with_camera_labels
----validation
--------segment-183829460855609442_430_000_450_000_with_camera_labels
------------找个OpenLane里面的真值json放进去，重命名成要推理的图片（这里主要是我只看可视化结果，对数值不在意，如果你有真的真值就放真的吧

```  

然后运行
```  
python main_persformer.py --mod=PersFormer --batch_size=1
```  

> 请问可以将单张推理的命令发一下吗

**Comment by Monssica** [comment]
thank you so much,are you trained model by yourself ?

**Comment by Monssica** [comment]
想请问您training的segment和validation的segment可以不一致吗？
![image](https://user-images.githubusercontent.com/51433003/186303205-617676b2-eb22-46a6-bd97-2f4124de9e61.png)
我按照这个格式修改后，训练时仍然报错，报错结果如下：
![image](https://user-images.githubusercontent.com/51433003/186303501-dd127246-df8a-4e98-b0c7-ae8020cc30a8.png)

**Comment by Monssica** [comment]
十分感谢，美好的一天~

**Comment by ZC0102-shu** [comment]
> 十分感谢，美好的一天~

请问你在其他数据上预测的效果如何？
