### ISSUE TITLE
Question for subprocess and zerodivision error

### ISSUE THREAD

**Issue by JasonKge** [OpenPerceptionX/PersFormer_3DLane#81]
Hello! When I run your code on the server after following your readme.md file configuration, I get **ZeroDivisionError** and **subprocess errors**, and sometimes it gets **RuntimeError: Address already in use**. The following screenshot shows the error. Could you please explain the solution? Thank you very much!
![微信截图_20221124013134](https://user-images.githubusercontent.com/104550250/203613794-21841a0c-b6b7-4b8e-a2ce-439c18de28fa.png)

**Comment by RicardLee** [comment]
"Address already in use" means that the main_port is used. It may be caused by that you lanuch 2 task at the same time.

**Comment by GCQi** [comment]
I am getting this error of "ZeroDivisionError: Weights sum to zero, can't be normalized", could you please support to fix
