### ISSUE TITLE
why sometimes one lane line is detected as two

### ISSUE THREAD

**Issue by linxcan** [OpenPerceptionX/PersFormer_3DLane#82]
Hi, thanks for the great work you do. We are getting ready to continue on your work. We have several questions. We tested under other data sets,  1) why sometimes one lane line is detected as two. 2) Lane line detection also has problems when going uphill and downhill.

**Comment by RicardLee** [comment]
The performance of PersFormer was not good enough and there are some imperfection where you con improve.
