### ISSUE TITLE
2D lane detection discrepancy

### ISSUE THREAD

**Issue by user-235813** [OpenPerceptionX/PersFormer_3DLane#84]
I tested the PersFormer model using these weights [[model_best_PersFormer_on_OpenLaneV1.1.pth.tar](https://drive.google.com/file/d/1TwjmFB3p3luCG8ytZ4MEI-TMoDT2Vn3G/view)] on this image [[152268801497018700.jpg](https://github.com/OpenPerceptionX/OpenLane/blob/main/eval/LANE_evaluation/lane2d/example/images/segment-10203656353524179475_7625_000_7645_000_with_camera_labels/152268801497018700.jpg)].

The 9 detected lines look like this:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/119571368/204996286-ef8a4521-7922-4927-bcc1-f282e9157c0a.png">

The sample result for the openlane example [[152268801497018700.json](https://github.com/OpenPerceptionX/OpenLane/blob/main/eval/LANE_evaluation/lane2d/example/results/segment-10203656353524179475_7625_000_7645_000_with_camera_labels/152268801497018700.json)] however has only 6 detected lines. I assume the results are using PersFormer trained on OpenLane. These results look like this:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/119571368/204999576-7a2e7547-0df2-47ea-b96b-55c67e6b24d5.png">

Do you have any thoughts about why my results are much worse?

**Comment by RicardLee** [comment]
Hi, the sample of [results](https://github.com/OpenPerceptionX/OpenLane/blob/main/eval/LANE_evaluation/lane2d/example/results/segment-10203656353524179475_7625_000_7645_000_with_camera_labels/152268801497018700.json) are not generated with the PersFormer model on OpenLane.

**Comment by user-235813** [comment]
@RicardLee, thank you for the quick response. Can you talk about the method/model that created the [sample results](https://github.com/OpenPerceptionX/OpenLane/blob/main/eval/LANE_evaluation/lane2d/example/results/segment-10203656353524179475_7625_000_7645_000_with_camera_labels/152268801497018700.json)? As a sanity check, do the PersFormer-OpenLane model results above look reasonable?

Another question is: At test time, will the 2D results get worse if the input extrinsics have error (or are completely wrong)? Or will the extrinsics only affect 3D results?

**Comment by hao-xiaoxing** [comment]
May I ask how you tested the above test results, can you post the test code?@ user-235813
