### ISSUE TITLE
模型和数据集坐标问题

### ISSUE THREAD

**Issue by cedricgsh** [OpenPerceptionX/PersFormer_3DLane#9]
非常感谢可以开源如此优秀的工作，关于模型和数据集我有一些问题想请教：
1）数据集中2d坐标和3d坐标是不是不存在对应关系，我发现2d坐标数量和3d坐标数量不一致
2）模型输出的是世界坐标系吗，我看到代码中是相机坐标系的gt转换到世界坐标系后再和pred进行匹配https://github.com/OpenPerceptionX/OpenLane/blob/main/eval/LANE_evaluation/lane3d/eval_3D_lane.py#L311，
@hli2020 @dyfcalid @ChonghaoSima

**Comment by dyfcalid** [comment]
Thank you for your issue.
1) 2D and 3D coordinates are corresponding and consistent.
2) The final lane lines of the model output and gt matching will be transformed to the ground coordinate system (world coordinate system) for the right hand coordinate system with the origin on the ground, y-axis pointing forward, x-axis to the right and z-axis up. Refer to the previous [issue#4](https://github.com/OpenPerceptionX/PersFormer_3DLane/issues/4).

**Comment by cedricgsh** [comment]
但是我发现在有的json文件中，2d点的数量和3d点的数量不一致，这样情况下2d坐标和3d坐标是如何对应的呢

**Comment by dyfcalid** [comment]
> 但是我发现在有的json文件中，2d点的数量和3d点的数量不一致，这样情况下2d坐标和3d坐标是如何对应的呢

Can you give an example?

**Comment by cedricgsh** [comment]
validation/segment-10203656353524179475_7625_000_7645_000_with_camera_labels/152268801497018700.json中，2d点的标注343个，3d点的标注1173个。

**Comment by dyfcalid** [comment]
Sorry, I've misunderstood your question. The lanes are corresponding, but it's true that there is **no one-to-one correspondence** between the **points** in 2d and 3d coordinates.

**Comment by cedricgsh** [comment]
Thank you so much.
