### ISSUE TITLE
推理代码

### ISSUE THREAD

**Issue by jackychancjcjcj** [OpenPerceptionX/PersFormer_3DLane#90]
请问下 这边有提供推理的代码可以测试效果吗

**Comment by RicardLee** [comment]
We recommend using English or English & Chinese for issues so that we could have broader discussion.

**Comment by RicardLee** [comment]
The repo provides the code and [tutorial](https://github.com/OpenPerceptionX/PersFormer_3DLane/blob/main/docs/TRAIN_VAL.md).

**Comment by jackychancjcjcj** [comment]
1
